Document: rasdaemon
Title: Debian rasdaemon Manual
Author: <insert document author here>
Abstract: This manual describes what rasdaemon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rasdaemon/rasdaemon.sgml.gz

Format: postscript
Files: /usr/share/doc/rasdaemon/rasdaemon.ps.gz

Format: text
Files: /usr/share/doc/rasdaemon/rasdaemon.text.gz

Format: HTML
Index: /usr/share/doc/rasdaemon/html/index.html
Files: /usr/share/doc/rasdaemon/html/*.html
